import express from "express";
import httpProxy from "http-proxy";
import fs from "node:fs";
import path from "node:path";

const PORT = Number.parseInt(process.env.PORT ?? "8080", 10);
const BACKEND_PORT = Number.parseInt(process.env.BACKEND_PORT ?? "5001", 10);
const BACKEND_TARGET = `http://127.0.0.1:${BACKEND_PORT}`;

// Railway provides these
const RAILWAY_PUBLIC_DOMAIN = process.env.RAILWAY_PUBLIC_DOMAIN;
const PUBLIC_URL = process.env.PUBLIC_URL || (RAILWAY_PUBLIC_DOMAIN ? `https://${RAILWAY_PUBLIC_DOMAIN}` : null);

// MiroFish state directory
const DATA_DIR = "/data";

// Required env vars for setup
const SETUP_PASSWORD = process.env.SETUP_PASSWORD?.trim();
const LLM_API_KEY = process.env.LLM_API_KEY?.trim();
const LLM_BASE_URL = process.env.LLM_BASE_URL?.trim();
const LLM_MODEL_NAME = process.env.LLM_MODEL_NAME?.trim();

console.log(`[mirofish] Starting at port ${PORT}`);
console.log(`[mirofish] Backend: ${BACKEND_TARGET}`);
console.log(`[mirofish] Public URL: ${PUBLIC_URL || "not configured"}`);

const app = express();
app.disable("x-powered-by");
app.use(express.json({ limit: "1mb" }));

// ============================================
// Setup Wizard Auth Middleware
// ============================================

function requireSetupAuth(req, res, next) {
  if (!SETUP_PASSWORD) {
    return res.status(500).type("text/plain").send(
      "SETUP_PASSWORD is not set. Set it in Railway Variables before using /setup."
    );
  }

  const header = req.headers.authorization || "";
  const [scheme, encoded] = header.split(" ");
  if (scheme !== "Basic" || !encoded) {
    res.set("WWW-Authenticate", 'Basic realm="MiroFish Setup"');
    return res.status(401).send("Auth required");
  }
  const decoded = Buffer.from(encoded, "base64").toString("utf8");
  const idx = decoded.indexOf(":");
  const password = idx >= 0 ? decoded.slice(idx + 1) : "";
  if (password !== SETUP_PASSWORD) {
    res.set("WWW-Authenticate", 'Basic realm="MiroFish Setup"');
    return res.status(401).send("Invalid password");
  }
  return next();
}

// ============================================
// Setup Wizard Static Files
// ============================================

app.get("/setup/app.js", requireSetupAuth, (_req, res) => {
  res.type("application/javascript");
  res.sendFile(path.join(process.cwd(), "src", "public", "setup-app.js"));
});

app.get("/setup/styles.css", requireSetupAuth, (_req, res) => {
  res.type("text/css");
  res.sendFile(path.join(process.cwd(), "src", "public", "styles.css"));
});

app.get("/setup", requireSetupAuth, (_req, res) => {
  res.sendFile(path.join(process.cwd(), "src", "public", "setup.html"));
});

app.get("/setup/healthz", (_req, res) => res.json({ ok: true }));

// ============================================
// Setup Wizard API
// ============================================

app.get("/setup/api/status", requireSetupAuth, (_req, res) => {
  const configured = Boolean(LLM_API_KEY && LLM_BASE_URL && LLM_MODEL_NAME);
  const domain = RAILWAY_PUBLIC_DOMAIN || "localhost";

  res.json({
    configured,
    domain,
    publicUrl: PUBLIC_URL,
    llm: {
      baseUrl: LLM_API_KEY || null,
      model: LLM_MODEL_NAME || null,
      hasKey: Boolean(LLM_API_KEY),
    },
  });
});

app.post("/setup/api/configure", requireSetupAuth, async (req, res) => {
  try {
    const { llmApiKey, llmBaseUrl, llmModelName, zepApiKey } = req.body || {};

    fs.mkdirSync(DATA_DIR, { recursive: true });

    const lines = [
      `# MiroFish Configuration - generated by setup wizard`,
      `LLM_API_KEY=${llmApiKey || LLM_API_KEY || ""}`,
      `LLM_BASE_URL=${llmBaseUrl || LLM_BASE_URL || "https://openrouter.ai/api/v1"}`,
      `LLM_MODEL_NAME=${llmModelName || LLM_MODEL_NAME || "openai/gpt-4o-mini"}`,
      `ZEP_API_KEY=${zepApiKey || process.env.ZEP_API_KEY || ""}`,
      `SECRET_KEY=${process.env.SECRET_KEY || "mirofish-dev-secret-change-me"}`,
      `BACKEND_PORT=${BACKEND_PORT}`,
    ];

    const envContent = lines.join("\n") + "\n";
    const envPath = path.join(DATA_DIR, ".env");
    fs.writeFileSync(envPath, envContent, { mode: 0o600 });

    console.log(`[setup] Configuration saved to ${envPath}`);

    res.json({
      ok: true,
      message: "Configuration saved. Restart the service to apply changes.",
      config: {
        llmBaseUrl: llmBaseUrl || LLM_BASE_URL,
        llmModelName: llmModelName || LLM_MODEL_NAME,
        hasZep: Boolean(zepApiKey),
      },
    });
  } catch (err) {
    console.error("[/setup/api/configure] error:", err);
    res.status(500).json({ ok: false, error: String(err) });
  }
});

app.get("/setup/api/models", requireSetupAuth, (_req, res) => {
  const models = [
    { id: "openai/gpt-4o-mini", name: "GPT-4o Mini", provider: "OpenAI", contextWindow: 128000, inputPrice: 0.15, outputPrice: 0.60 },
    { id: "openai/gpt-4o", name: "GPT-4o", provider: "OpenAI", contextWindow: 128000, inputPrice: 2.50, outputPrice: 10.00 },
    { id: "anthropic/claude-sonnet-4", name: "Claude Sonnet 4", provider: "Anthropic", contextWindow: 200000, inputPrice: 3.00, outputPrice: 15.00 },
    { id: "anthropic/claude-3-5-sonnet-latest", name: "Claude 3.5 Sonnet", provider: "Anthropic", contextWindow: 200000, inputPrice: 3.00, outputPrice: 15.00 },
    { id: "google/gemini-2.5-pro-preview", name: "Gemini 2.5 Pro", provider: "Google", contextWindow: 1048576, inputPrice: 1.25, outputPrice: 10.00 },
    { id: "google/gemini-3-flash-preview", name: "Gemini 3 Flash", provider: "Google", contextWindow: 1048576, inputPrice: 0.10, outputPrice: 0.40 },
    { id: "deepseek/deepseek-chat-v3-0324", name: "DeepSeek V3", provider: "DeepSeek", contextWindow: 131072, inputPrice: 0.27, outputPrice: 1.10 },
    { id: "meta-llama/llama-3.3-70b-instruct", name: "Llama 3.3 70B", provider: "Meta", contextWindow: 131072, inputPrice: 0.40, outputPrice: 0.90 },
    { id: "mistralai/mistral-nemo", name: "Mistral Nemo", provider: "Mistral", contextWindow: 128000, inputPrice: 0.15, outputPrice: 0.15 },
    { id: "qwen/qwen-3.5-397ba17b", name: "Qwen 3.5", provider: "Qwen", contextWindow: 262144, inputPrice: 0.50, outputPrice: 2.00 },
  ];

  res.json({ ok: true, models });
});

app.post("/setup/api/reset", requireSetupAuth, async (_req, res) => {
  try {
    const envPath = path.join(DATA_DIR, ".env");
    fs.rmSync(envPath, { force: true });
    res.type("text/plain").send("OK - configuration reset.");
  } catch (err) {
    res.status(500).type("text/plain").send(String(err));
  }
});

// ============================================
// API Proxy → Backend (5001)
// ============================================

const apiProxy = httpProxy.createProxyServer({
  target: BACKEND_TARGET,
  ws: true,
  xfwd: false,
});

apiProxy.on("error", (err, _req, res) => {
  console.error("[api-proxy]", err?.message || err);
  if (!res.headersSent) {
    res.status(502).json({ ok: false, error: "Backend error" });
  }
});

// API routes → backend (5001)
app.use("/api", (req, res) => {
  apiProxy.web(req, res, { target: BACKEND_TARGET });
});

app.use("/api/ws", (req, socket, head) => {
  apiProxy.ws(req, socket, head, { target: BACKEND_TARGET });
});

// WebSocket upgrade for backend
app.use((req, res, next) => {
  if (req.path.startsWith("/ws") || req.url.includes("websocket")) {
    return apiProxy.web(req, res, { target: BACKEND_TARGET });
  }
  next();
});

// ============================================
// Static Files — serve built Vue frontend
// (must be after API routes so /api/* is never matched here)
// ============================================

const distPath = "/app/frontend/dist";
app.use(express.static(distPath));

// SPA fallback — serve index.html for any unmatched route
app.use((_req, res) => {
  res.sendFile(path.join(distPath, "index.html"));
});

// ============================================
// Server
// ============================================

const server = app.listen(PORT, () => {
  console.log(`[mirofish] Listening on port ${PORT}`);
  console.log(`[mirofish] Setup wizard: http://localhost:${PORT}/setup`);
  console.log(`[mirofish] API → ${BACKEND_TARGET}`);
});

server.on("upgrade", (req, socket, head) => {
  if (req.url?.includes("/ws") || req.url?.includes("websocket")) {
    apiProxy.ws(req, socket, head, { target: BACKEND_TARGET });
  }
});

process.on("SIGTERM", () => {
  console.log("[mirofish] Shutting down...");
  server.close(() => {
    console.log("[mirofish] Stopped.");
    process.exit(0);
  });
});
